name: Web Scraping Job

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python py/req.py > index.html

    - name: Display output
      run: cat index.html
